### ISSUE TITLE
Error creating new block app

### ISSUE THREAD

**Issue by ajpocus** [blockprotocol/blockprotocol#161]
I'm trying to create a new block app, with the instructions [on this page](https://blockprotocol.org/docs/developing-blocks#install) [edit: added link]. I use the following commands:

```
npx create-block-app test-block
cd test-block
yarn install
```

The `yarn install` command fails with the following error:

```
[3/4] ⠈ mock-block-dock
error /Users/austin/projects/test-block/node_modules/mock-block-dock: Command failed.
Exit code: 1
Command: yarn build
Arguments:
Directory: /Users/austin/projects/test-block/node_modules/mock-block-dock
Output:
yarn run v1.22.17
$ yarn clean; yarn build:cjs; yarn build:esm
$ rimraf ./dist/
$ tsc --p tsconfig.build.json --module commonjs --outDir dist/cjs
error TS5058: The specified path does not exist: 'tsconfig.build.json'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
$ tsc --p tsconfig.build.json
error TS5058: The specified path does not exist: 'tsconfig.build.json'.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm on macOS version 12.1 / Node v16.3.1 / npm v8.4.0 / yarn 1.22.17. Please let me know if you need any more details -- I'd really like to contribute to this project. Thanks in advance!

**Comment by gwenevieve** [comment]
+1 it would be nice to be able to have it install correctly out of the box :). I was able to get it working with a global install of `rimraf` and re-insalling `tsc` but definitely took a bit of debugging on my end. 

MacOS 12.0.1 / Node v14.17.5 / npm v6.14.14 / yarn 1.17.3

**Comment by kachkaev** [comment]
I just published [`block-template`](https://www.npmjs.com/package/block-template)`@0.0.4` and [`mock-block-dock`](https://www.npmjs.com/package/mock-block-dock)`@0.0.4`. I hope that it fixes the issue with `yarn install` 🤞

Please let us know if you still experiencing any errors! And thanks for reporting! 🙌

I am going to upgrade some dev dependencies soon – see https://github.com/blockprotocol/blockprotocol/issues/162 and #168 for context. Our `create-block-app` DX is still a bit raw, but we plan to improve it in the upcoming weeks!
