### ISSUE TITLE
create-block-app could do with modernisation

### ISSUE THREAD

**Issue by GordonSmith** [blockprotocol/blockprotocol#162]
The generated app feels a little outdated:
* It doesn't support nullish coalescing (in my case in an imported es6 third party module)
* Using old versions of webpack
* Uses outdated version of babel (why is it using babel in a typescript project?) 

FWIW I see the potential and have some components that would be very suitable with very little work, but the lack of nullish coalescing and my unfamiliarity with babel started to make it a chore.

I don't mean to be negative, and am sorry that the above is all I can contribute at the moment,

**Comment by kachkaev** [comment]
Thanks for your feedback @GordonSmith! We released `mock-block-dock@0.0.5` and `block-template@0.0.6` which include the latest webpack and babel dependencies. Let us know what you think!

These dependency updates are just the first step. We are planning to simplify block DX in the coming weeks, so stay tuned! Feel free to share any ideas! 🙌
