### ISSUE TITLE
[SPEC] Fix example data on providing-data section of docs site

### ISSUE THREAD

**Issue by IDisposable** [blockprotocol/blockprotocol#176]
On [the page documenting how to link data between entities](https://blockprotocol.org/docs/embedding-blocks#providing-data) the example for the user has an `entityId` of `41` but the related example shows the `linkId` and `relatedSourceId` having a value of `42`. This inconsistent example is confusing.

id | name | companyId
-- | -- | --
41 | Bob | 456

```
{
  "entityId": "41",
  "entityTypeId": "User",
  "name": "Bob"
}

{
  "linkId": "user-42-company-456",
  "sourceEntityId": "42",
  "destinationEntityId": "456",
  "path": "company"
}
```

If there a place we can submit PRs to the  _docs_ site?

**Comment by CiaranMn** [comment]
Thanks @IDisposable - this is a fair flag, these should be consistent.

You're welcome to submit a PR amending [this file](https://github.com/blockprotocol/blockprotocol/blob/main/site/src/_pages/docs/3_embedding-blocks.mdx) to correct the references, if you're up for it!

**Comment by IDisposable** [comment]
PR created and CLA signed. :)

**Comment by CiaranMn** [comment]
Thank you! If you spot anything else that needs improving please flag it or create a PR.

We'd love any general feedback you have too - either in [discussions](https://github.com/blockprotocol/blockprotocol/discussions) or in our [Discord](https://blockprotocol.org/discord). 

Thanks again and welcome 😁
