### ISSUE TITLE
[SITE] i18n support

### ISSUE THREAD

**Issue by nonparibus** [blockprotocol/blockprotocol#234]
Community members in China have reached out to us about providing translations of the specification and docs site.

We use NextJS on the Block Protocol website. This makes it easy to support internationalization of content, but some set up work is required. See https://nextjs.org/docs/advanced-features/i18n-routing

We're interested in hearing from community members with interest in helping us get the site ready for i18n, or who wish to provide translations.

**Comment by nonparibus** [comment]
We've had separate expressions of interest regarding translation of the site into Spanish.

**Comment by m1911star** [comment]
Hi there, I would like to help with i18n support, but I wonder if I can decide which option to choose, here is the difference：

- sub-path-routing: this will introduce route like `https://blockprotocol.org/zh-CN/docs` 
- domain-routing: this will need multi domains

I think we can choose option 1？

Also, next.js does not support content translation by default, I decide to use https://github.com/isaachinman/next-i18next, any advice?

**Comment by nonparibus** [comment]
> Hi there, I would like to help with i18n support, but I wonder if I can decide which option to choose, here is the difference：
> 
> 
> 
> - sub-path-routing: this will introduce route like `https://blockprotocol.org/zh-CN/docs` 
> 
> - domain-routing: this will need multi domains
> 
> 
> 
> I prefer option 1, any advice?
> 
> 
> 
> Also, next.js does not support content translation by default, I decide to use https://github.com/isaachinman/next-i18next, any advice?

Definite preference for option 1 our side, too. Thanks for your interest in moving this forward. Cc @kachkaev from our BP core team re: implementation guidance.

**Comment by m1911star** [comment]
Hi, I just finished a prototype with i18n and create a pr. https://github.com/blockprotocol/blockprotocol/pull/451

Now I'm fixing docs page 404 error. 

Also looking for help with complete content translations~ sincerely look forward to your advice~

**Comment by nonparibus** [comment]
Thanks, @m1911star! CCing @0xDing and @tsui66 who both have eyes 👀 on this, in case either is in a position to help with content translations in #451.

**Comment by nonparibus** [comment]
CCing @imchell who raised another big FE/UI topic and may also be interested in the translation piece.
