### ISSUE TITLE
[REPO] Update root README to document new packages

### ISSUE THREAD

**Issue by nonparibus** [blockprotocol/blockprotocol#299]
@CiaranMn Please can you add new package summaries to section 2 of the ‘Repository contents’ bit of the root README.md — it contains 4 pkgs, but we now have a few more that can be added: https://github.com/blockprotocol/blockprotocol/tree/main/packages Cheers.

**Comment by CiaranMn** [comment]
Addressed in https://github.com/blockprotocol/blockprotocol/pull/348
